### ISSUE TITLE
two routes with same put but different method will clash

### ISSUE THREAD

**Issue by mcollina** [cemremengu/fastify-routes#1]
As titled.

**Comment by cemremengu** [comment]
@mcollina  Should methods be a list (as I did now) or another Map ?

**Comment by mcollina** [comment]
I would use a `{ get, post, head }` type of object, not a `Map`.

**Comment by cemremengu** [comment]
Could you please check daa2f85f0199461066f16c3ea579684d11a66d4f ?

Thanks for taking your time to have a look!

**Comment by mcollina** [comment]
ok for me

Il giorno mer 19 set 2018 alle 13:55 Cemre Mengu <notifications@github.com>
ha scritto:
